export const locationMapping = {
    "All": "全部",
    "Random": "隨機",
    "Jincheng": "金城",
    "Jinning": "金寧",
    "Jinhu": "金湖",
    "Jinsha": "金沙",
    "Lieyu": "烈嶼" 
};

export const genreMapping = {
    "All": "全部",
    "Random": "隨機",
    "Bento": "便當菜/快餐",
    "Japanese": "日式料理",
    "HotPot": "小火鍋",
    "Chinese": "中式餐廳",
    "FastFood": "速食",
    "American": "美式餐廳",
    "Italian": "義式料理",
    "Breakfast": "早餐店",
    "Noodles": "麵店",
    "Vegetarian": "素食",
    "BreakfastBrunch": "早午餐",
    "Steak": "牛排館",
    "Ramen": "拉麵店",
    "SouthEastAsian": "東南亞料理",
    "Dessert":"甜點店",
    "LouMei":"滷味",
    "Bar":"酒吧",
    "Cafe":"咖啡廳",
    "Buffet":"自助餐",
    "Indian":"印度",
    "Light":"輕食",
    "Korean":"韓式料理",
    "HongKong":"港式料理",
    "Exotic":"異國料理",
    "French":"法式料理",
    "NightSnack":"宵夜",
    "Drinks":"飲料"
}